#pragma once
#include <seabass/base/context.h>
#include <seabass/base/opengl_loader.h>
#include <seabass/base/program.h>
#include <seabass/base/recorder.h>
#include <seabass/base/themes.h>
#include <seabass/base/vertex_array.h>
#include <seabass/base/vertex_buffer.h>
#include <seabass/base/window.h>
#include <seabass/imgui/image.h>
#include <seabass/loader/icl_trajectory.h>
#include <seabass/loader/trajectory.h>
#include <seabass/loader/tum_trajectory.h>
#include <seabass/widgets/widgets.h>
